FROM node:12.16.1

RUN apt-get update && apt-get install chromium -y && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/api

# For npm@5 or later, copy package-lock.json as well
COPY ./package.json ./package-lock.json ./

RUN npm install -g nodemon

RUN npm install

COPY . .

EXPOSE 8081
